apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- keycloak.yaml

# Rewritten by jarvis-keycloak's own Jenkinsfile "Bump manifest" stage
# after each image push — see backend/kustomization.yaml for the same
# pattern.
images:
- name: jarvis-keycloak
  newName: host.minikube.internal:5050/root/jarvis-keycloak
  newTag: f2b1fd13
