apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: jarvis-agent-sandbox-router
  namespace: argocd
spec:
  project: default
  source:
    repoURL: http://host.minikube.internal:8929/root/jarvis-deploy.git
    targetRevision: main
    path: agent-sandbox-router/overlays/test
  destination:
    server: https://kubernetes.default.svc
    namespace: agent-sandbox-system
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
