apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: jarvis-file-service
  namespace: argocd
spec:
  project: default
  source:
    repoURL: http://host.minikube.internal:8929/root/jarvis-deploy.git
    targetRevision: main
    path: file-service/overlays/test
  destination:
    server: https://kubernetes.default.svc
    namespace: jarvis
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
