apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: jarvis-staging-frontend
  namespace: argocd
spec:
  project: default
  source:
    repoURL: http://host.minikube.internal:8929/root/jarvis-deploy.git
    targetRevision: staging
    path: frontend
  destination:
    server: https://host.minikube.internal:18443
    namespace: jarvis
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
